### ISSUE TITLE
Be able to run multiple operations without having to re-invoke mbeanz

### ISSUE THREAD

**Issue by oliverdrake** [ojung/mbeanz#11]
Currently if I want to run multiple operations, I need to start mbeanz each time, would be nice to be able to start mbeanz once, run all my operations and either leave mbeanz running or kill it with ctrl+c

**Comment by ojung** [comment]
Hm, that may actually make sense. May be non-trivial to implement though.
Would it help to be able to select multiple mbeans in the fuzzy finder, then be prompted to provide the arguments and have the operations invoked sequentially?

**Comment by oliverdrake** [comment]
Yeh that might be nice too. You probably won't always know the sequence up front though, during testing you might hit one mbean, look at the output, then decide which mbeans to hit next to find out more information about a particular problem.

**Comment by ojung** [comment]
Hm, I'm not sure. Do you mean it should have like a command mode?
e.g.:
- you type `mbeanz adscale`
- fuzzy finder lets you search operation
- (if there is more than one signature you get to choose one)
- (if there are any args you get prompted to enter them)
- it prints the response
- it enters a command mode waiting for an input (for example: `n - next, q - quit:`) while the output of the previous operation is still visible

`git add --patch` has a similar mode of operation.

**Comment by oliverdrake** [comment]
Yeh that's pretty much what I'm after. But yeh I see now the problem of having to display the previous output before invoking fuzzy find again, maybe it's not such a great idea... I guess I could make myself a short alias for mbeanz adscale
